function reports(){

  const m = load(DB.MED);
  const s = load(DB.SALES);

  let revenue = s.reduce((a,b)=>a+b.total,0);

  let txt = `
========================
PHARMACY REPORT V11
========================
DATE: ${new Date().toISOString()}

--- INVENTORY ---
`;

  m.forEach(x=>{
    txt += `- ${x.name} | Qty:${x.quantity} | Price:${x.price} | Exp:${x.expiry}\n`;
  });

  txt += `

--- SALES ---
TOTAL SALES: ${s.length}
REVENUE: ${revenue}

`;

  s.forEach(x=>{
    txt += `- ${x.medicine} | Qty:${x.qty} | Total:${x.total} | Date:${x.date}\n`;
  });

  fs.writeFileSync(
    'reports/pharmacy_report.txt',
    txt
  );

  let tex = `
\\documentclass[11pt,a4paper]{article}

\\usepackage[a4paper,margin=1in]{geometry}
\\usepackage[dvipsnames]{xcolor}
\\usepackage{longtable}
\\usepackage{booktabs}
\\usepackage{hyperref}

\\title{\\textbf{Pharmacy Management System V11}}
\\author{Termux Pharmacy Platform}
\\date{\\today}

\\begin{document}

\\maketitle

\\section*{Executive Summary}

This report was automatically generated by the Pharmacy Management System V11.

\\section*{Inventory Summary}

\\begin{longtable}{lrrl}
\\toprule
Medicine & Qty & Price & Expiry \\\\
\\midrule
`;

  m.forEach(x=>{
    tex += `${x.name} & ${x.quantity} & ${x.price} & ${x.expiry} \\\\\n`;
  });

  tex += `
\\bottomrule
\\end{longtable}

\\section*{Sales Summary}

Total Sales: ${s.length}

Total Revenue: ${revenue}

\\begin{longtable}{lrrl}
\\toprule
Medicine & Qty & Total & Date \\\\
\\midrule
`;

  s.forEach(x=>{
    tex += `${x.medicine} & ${x.qty} & ${x.total} & ${x.date} \\\\\n`;
  });

  tex += `
\\bottomrule
\\end{longtable}

\\section*{System Highlights}

\\begin{itemize}
\\item Inventory Management
\\item Sales Processing
\\item Analytics Engine
\\item SAS Export
\\item Backup System
\\item Audit Logging
\\item Health Monitoring
\\item Web Dashboard
\\end{itemize}

\\section*{Future Additions}

\\begin{itemize}
\\item AI Demand Forecasting
\\item Expiry Prediction
\\item Barcode Scanning
\\item QR Code Support
\\item Multi-Branch Pharmacies
\\item Cloud Synchronization
\\item Advanced SAS Analytics
\\end{itemize}

\\end{document}
`;

  fs.writeFileSync(
    'reports/pharmacy_report.tex',
    tex
  );

  try {

    const { execSync } = require('child_process');

    execSync(
      process.env.HOME +
      '/compiletex1.sh reports/pharmacy_report.tex',
      {stdio:'inherit'}
    );

    console.log('TXT report generated.');
    console.log('LaTeX report generated.');
    console.log('PDF report generated.');

  } catch(e) {

    console.log('TXT report generated.');
    console.log('LaTeX report generated.');
    console.log('PDF compilation skipped.');

  }

  pause();

}


